import type { SidebarConfig } from 'vuepress'
// NOTE: Generated by "npm run gen-sidebar". Build will fail if file doesn't exist.
import autoSidebar from './sidebar.auto.json'
import { wayfindingZhGroup } from './sidebar-shared.js'

const introSection = {
  text: '地月空间是什么（环境与概念入门）',
  collapsible: false,
  children: [
    '/what-is-cislunarspace/',
    '/what-is-cislunarspace/environment',
  ],
}

const orbitsSection = {
  text: '地月空间飞行器运行轨道（任务轨道基础）',
  collapsible: false,
  children: ['/cislunar-orbits/'],
}

const researchSection = {
  text: '地月空间科学研究前沿（方向 · 机构 · 项目）',
  collapsible: false,
  children: [
    '/research-frontiers/',
    {
      text: '研究方向',
      link: '/research-frontiers/directions/',
      collapsible: true,
      children: [
        '/research-frontiers/directions/strategy',
        '/research-frontiers/directions/low-energy-transfer',
        '/research-frontiers/directions/orbit-characterization',
        '/research-frontiers/directions/simulation-systems',
        {
          text: '地月空间轨道博弈',
          link: '/research-frontiers/directions/orbital-game/',
          collapsible: true,
          children: [
            '/research-frontiers/directions/orbital-game/orbital-game-inspection',
          ],
        },
      ],
    },
    {
      text: '研究机构和组织',
      link: '/research-frontiers/institutions/',
      collapsible: true,
      children: [
        '/research-frontiers/institutions/nudt',
        '/research-frontiers/institutions/npu',
        '/research-frontiers/institutions/hit',
        '/research-frontiers/institutions/seu',
        '/research-frontiers/institutions/dfhscl',
        '/research-frontiers/institutions/thu',
      ],
    },
    '/research-frontiers/journals-conferences',
    '/research-frontiers/major-projects',
  ],
}

/** 首页：仅全站导览，不展开各栏目详细目录 */
const homeSidebar = [wayfindingZhGroup]

const whatIsCislunarspaceSidebar = [wayfindingZhGroup, introSection]
const cislunarOrbitsMainSidebar = [wayfindingZhGroup, orbitsSection]
const researchFrontiersMainSidebar = [wayfindingZhGroup, researchSection]

const glossarySidebar = [
  wayfindingZhGroup,
  {
    text: '地月空间术语词典（定义与概念检索）',
    collapsible: false,
    children: [
      '/glossary/',
      {
        text: '动力学模型',
        collapsible: true,
        children: [
          '/glossary/cr3bp',
          '/glossary/qbcp',
          '/glossary/ephemeris-model',
        ],
      },
      {
        text: '任务轨道',
        collapsible: true,
        children: ['/glossary/dro', '/glossary/nrho'],
      },
      {
        text: '导航技术',
        collapsible: true,
        children: ['/glossary/xray-pulsar-navigation'],
      },
    ],
  },
]

const resourcesToolsSidebar = [
  wayfindingZhGroup,
  {
    text: '资源与工具（数据、代码与数据集）',
    collapsible: false,
    children: [
      '/resources-tools/',
      '/resources-tools/e2m2e',
      '/resources-tools/scipy',
      '/resources-tools/r2s2',
      '/resources-tools/datasets',
    ],
  },
]

const spaceNewsSidebar: SidebarConfig[''] = []

const blueTeamResearchSidebar = [
  wayfindingZhGroup,
  {
    text: '蓝军研究',
    collapsible: false,
    children: [
      {
        text: '作战条令研究',
        link: '/blue-team-research/doctrine-strategy/',
        collapsible: true,
        children: [
          '/blue-team-research/doctrine-strategy/',
          '/blue-team-research/doctrine-strategy/us-doctrine-system',
          '/blue-team-research/doctrine-strategy/joint-warfighting-doctrine',
          '/blue-team-research/doctrine-strategy/cyberspace-operations-doctrine',
        ],
      },
      {
        text: '装备与技术发展',
        link: '/blue-team-research/equipment-tech/',
        collapsible: true,
        children: [
          '/blue-team-research/equipment-tech/',
          '/blue-team-research/equipment-tech/sda-programs',
          '/blue-team-research/equipment-tech/spacex-role',
          '/blue-team-research/equipment-tech/architecture-programs',
          '/blue-team-research/equipment-tech/commercial-participation',
        ],
      },
      {
        text: '作战应用与聚焦场景',
        link: '/blue-team-research/operations-application/',
        collapsible: true,
        children: [
          '/blue-team-research/operations-application/',
          '/blue-team-research/operations-application/regional-conflicts',
          '/blue-team-research/operations-application/orbital-confrontation',
          '/blue-team-research/operations-application/kill-chain-focus',
          '/blue-team-research/operations-application/scenario-analysis',
          '/blue-team-research/operations-application/crosswalk',
        ],
      },
      {
        text: '资料共享与知识库',
        link: '/blue-team-research/knowledge-rag/',
        collapsible: true,
        children: [
          '/blue-team-research/knowledge-rag/',
          '/blue-team-research/knowledge-rag/search-metadata',
          '/blue-team-research/knowledge-rag/rag-roadmap',
        ],
      },
    ],
  },
]

export default <SidebarConfig>{
  '/glossary/': glossarySidebar,
  '/resources-tools/': resourcesToolsSidebar,
  '/blue-team-research/': blueTeamResearchSidebar,
  '/space-news/': spaceNewsSidebar,
  '/en/space-news/': spaceNewsSidebar,
  /** 全屏教学沙盘：不挂载目录型侧边栏（导航用顶栏即可） */
  '/satellite-simulation/': false,
  '/what-is-cislunarspace/': whatIsCislunarspaceSidebar,
  '/cislunar-orbits/': cislunarOrbitsMainSidebar,
  '/research-frontiers/': researchFrontiersMainSidebar,
  '/': homeSidebar,
}
