import type { SidebarConfig } from 'vuepress'
// NOTE: Generated by "npm run gen-sidebar". Build will fail if file doesn't exist.
import autoSidebar from './sidebar.auto.json'
import { wayfindingZhGroup } from './sidebar-shared.js'

const introSection = {
  text: '地月空间是什么（环境与概念入门）',
  collapsible: false,
  children: [
    '/what-is-cislunarspace/',
    '/what-is-cislunarspace/environment',
  ],
}

const orbitsSection = {
  text: '地月空间飞行器运行轨道（任务轨道基础）',
  collapsible: false,
  children: [
    '/cislunar-orbits/',
    {
      text: 'NRHO（近直线晕轨道）',
      link: '/cislunar-orbits/nrho/',
      collapsible: true,
      children: [
        '/cislunar-orbits/nrho/',
        '/cislunar-orbits/nrho/l1-nrho',
        '/cislunar-orbits/nrho/l2-nrho',
        '/cislunar-orbits/nrho/stability-maintenance',
        '/cislunar-orbits/nrho/gateway-cases',
        '/cislunar-orbits/nrho/design-parameters',
      ],
    },
    {
      text: 'DRO（远距离逆行轨道）',
      link: '/cislunar-orbits/dro/',
      collapsible: true,
      children: [
        '/cislunar-orbits/dro/',
        '/cislunar-orbits/dro/mechanics',
        '/cislunar-orbits/dro/family-classification',
        '/cislunar-orbits/dro/applications',
        '/cislunar-orbits/dro/design-method',
      ],
    },
    {
      text: '地月转移轨道',
      link: '/cislunar-orbits/transfer/',
      collapsible: true,
      children: [
        '/cislunar-orbits/transfer/',
        '/cislunar-orbits/transfer/tli-overview',
        '/cislunar-orbits/transfer/ballistic-capture',
        '/cislunar-orbits/transfer/corridor-design',
        '/cislunar-orbits/transfer/launch-windows',
      ],
    },
  ],
}

const researchSection = {
  text: '地月空间科学研究前沿（方向 · 机构 · 项目）',
  collapsible: false,
  children: [
    '/research-frontiers/',
    {
      text: '研究方向',
      link: '/research-frontiers/directions/',
      collapsible: true,
      children: [
        {
          text: '轨道设计与优化',
          link: '/research-frontiers/directions/orbit-design/',
          collapsible: true,
          children: [
            '/research-frontiers/directions/orbit-design/low-energy-transfer',
            '/research-frontiers/directions/orbit-design/orbit-characterization',
          ],
        },
        {
          text: '导航与定轨',
          link: '/research-frontiers/directions/navigation/',
          collapsible: true,
          children: [],
        },
        {
          text: '空间态势感知',
          link: '/research-frontiers/directions/ssa/',
          collapsible: true,
          children: [],
        },
        {
          text: '通信与信息网络',
          link: '/research-frontiers/directions/communication/',
          collapsible: true,
          children: [],
        },
        {
          text: '时空基准与测量',
          link: '/research-frontiers/directions/reference-frame/',
          collapsible: true,
          children: [],
        },
        {
          text: '航天运输体系',
          link: '/research-frontiers/directions/transportation/',
          collapsible: true,
          children: [],
        },
        {
          text: '编队飞行',
          link: '/research-frontiers/directions/formation-flying/',
          collapsible: true,
          children: [],
        },
        {
          text: '安全与治理',
          link: '/research-frontiers/directions/security-governance/',
          collapsible: true,
          children: [
            '/research-frontiers/directions/security-governance/strategy',
            {
              text: '地月空间轨道博弈',
              link: '/research-frontiers/directions/security-governance/orbital-game/',
              collapsible: true,
              children: [
                '/research-frontiers/directions/security-governance/orbital-game/orbital-game-inspection',
              ],
            },
          ],
        },
        {
          text: '基础设施与经济',
          link: '/research-frontiers/directions/infrastructure/',
          collapsible: true,
          children: [],
        },
        {
          text: '仿真系统',
          link: '/research-frontiers/directions/simulation/',
          collapsible: true,
          children: [
            '/research-frontiers/directions/simulation/simulation-systems',
          ],
        },
      ],
    },
    {
      text: '研究机构和组织',
      link: '/research-frontiers/institutions/',
      collapsible: true,
      children: [
        '/research-frontiers/institutions/nudt',
        '/research-frontiers/institutions/npu',
        '/research-frontiers/institutions/hit',
        '/research-frontiers/institutions/seu',
        '/research-frontiers/institutions/dfhscl',
        '/research-frontiers/institutions/thu',
      ],
    },
    '/research-frontiers/journals-conferences',
    '/research-frontiers/major-projects',
  ],
}

/** 首页：仅全站导览，不展开各栏目详细目录 */
const homeSidebar = [wayfindingZhGroup]

const whatIsCislunarspaceSidebar = [wayfindingZhGroup, introSection]
const cislunarOrbitsMainSidebar = [wayfindingZhGroup, orbitsSection]
const researchFrontiersMainSidebar = [wayfindingZhGroup, researchSection]

const glossarySidebar = [
  wayfindingZhGroup,
  {
    text: '地月空间术语词典（定义与概念检索）',
    collapsible: false,
    children: [
      '/glossary/',
      {
        text: '动力学与数学基础',
        collapsible: true,
        children: [
          '/glossary/dynamics/cr3bp',
          '/glossary/dynamics/cr3bp-lt',
          '/glossary/dynamics/a2ppo',
          '/glossary/dynamics/curriculum-learning',
          '/glossary/dynamics/lt-transfer-mdp',
          '/glossary/dynamics/gae',
          '/glossary/dynamics/direct-collocation',
          '/glossary/dynamics/qbcp',
          '/glossary/dynamics/ephemeris-model',
          '/glossary/dynamics/action-angle',
          '/glossary/dynamics/birkhoff-gustavson',
          '/glossary/dynamics/central-manifold',
          '/glossary/dynamics/poincare-section',
        ],
      },
      {
        text: '任务轨道',
        collapsible: true,
        children: [
          '/glossary/orbits/dro',
          '/glossary/orbits/nrho',
          '/glossary/orbits/eml-halo',
          '/glossary/orbits/dro-constellation',
        ],
      },
      {
        text: '导航技术与系统',
        collapsible: true,
        children: [
          '/glossary/navigation/xray-pulsar-navigation',
          '/glossary/navigation/gnss-weak-signal-navigation',
          '/glossary/navigation/inter-satellite-link-navigation',
          '/glossary/navigation/earth-moon-hybrid-navigation',
          '/glossary/navigation/orbit-identification',
          '/glossary/navigation/cislunar-spatiotemporal-reference',
          '/glossary/navigation/lunanet',
          '/glossary/navigation/moonlight',
          '/glossary/navigation/lunar-navigation-constellation',
          '/glossary/navigation/tiandu-1',
        ],
      },
      {
        text: '月球矿物',
        collapsible: true,
        children: [
          '/glossary/minerals/mg-changeite',
          '/glossary/minerals/ce-changeite',
        ],
      },
      {
        text: '项目与任务',
        collapsible: true,
        children: [
          '/glossary/programs/artemis',
          '/glossary/programs/lugre',
        ],
      },
      {
        text: '其他技术',
        collapsible: true,
        children: [
          '/glossary/other/pogo',
          '/glossary/other/exosims',
          '/glossary/other/space-traffic-management',
          '/glossary/other/starshade',
          '/glossary/other/nuclear-thermal-propulsion',
          '/glossary/other/cislunar-navigation-prospects',
        ],
      },
      {
        text: '机构和组织',
        collapsible: true,
        children: [
          '/glossary/organizations/anduril',
          '/glossary/organizations/booz-allen-hamilton',
          '/glossary/organizations/general-dynamics-mission-systems',
          '/glossary/organizations/gitai-usa',
          '/glossary/organizations/lockheed-martin',
          '/glossary/organizations/northrop-grumman',
          '/glossary/organizations/quindar',
          '/glossary/organizations/raytheon',
          '/glossary/organizations/sci-tec',
          '/glossary/organizations/spacex',
          '/glossary/organizations/true-anomaly',
          '/glossary/organizations/turion-space',
        ],
      },
    ],
  },
]

const backgroundSidebar = [
  wayfindingZhGroup,
  {
    text: '背景知识（基础理论 · 数学工具）',
    collapsible: false,
    children: [
      '/background/',
      {
        text: '数学工具',
        collapsible: true,
        children: [
          '/background/math/shooting-method',
          '/background/math/continuation',
          '/background/math/symplectic-integrator',
        ],
      },
      {
        text: '天体力学基础',
        collapsible: true,
        children: [
          '/background/mechanics/perturbation',
        ],
      },
      {
        text: '控制与优化',
        collapsible: true,
        children: [
          '/background/control/optimal-control',
        ],
      },
    ],
  },
]

const resourcesToolsSidebar = [
  wayfindingZhGroup,
  {
    text: '资源与工具（数据、代码与数据集）',
    collapsible: false,
    children: [
      '/resources-tools/',
      {
        text: '仿真软件',
        collapsible: true,
        children: [
          '/resources-tools/gmat',
          '/resources-tools/stk',
          '/resources-tools/atk',
          '/resources-tools/cesium',
        ],
      },
      {
        text: '核心算法库',
        collapsible: true,
        children: [
          '/resources-tools/e2m2e',
          '/resources-tools/scipy',
          '/resources-tools/r2s2',
          '/resources-tools/orekit',
          '/resources-tools/poliastro',
          '/resources-tools/basilisk',
          '/resources-tools/pykep',
        ],
      },
      {
        text: '数据资源',
        collapsible: true,
        children: [
          '/resources-tools/datasets',
        ],
      },
      {
        text: 'AI与云平台',
        collapsible: true,
        children: [
          '/resources-tools/digital-lunar',
          '/resources-tools/llm',
          '/resources-tools/naoc-data',
        ],
      },
    ],
  },
]

const spaceNewsSidebar: SidebarConfig[''] = []

const blueTeamResearchSidebar = [
  wayfindingZhGroup,
  {
    text: '蓝军研究',
    collapsible: false,
    children: [
      {
        text: '作战条令研究',
        link: '/blue-team-research/doctrine-strategy/',
        collapsible: true,
        children: [
          '/blue-team-research/doctrine-strategy/',
          '/blue-team-research/doctrine-strategy/us-doctrine-system',
          '/blue-team-research/doctrine-strategy/joint-warfighting-doctrine',
          '/blue-team-research/doctrine-strategy/cyberspace-operations-doctrine',
        ],
      },
      {
        text: '装备与技术发展',
        link: '/blue-team-research/equipment-tech/',
        collapsible: true,
        children: [
          '/blue-team-research/equipment-tech/',
          '/blue-team-research/equipment-tech/sda-programs',
          '/blue-team-research/equipment-tech/spacex-role',
          '/blue-team-research/equipment-tech/architecture-programs',
          '/blue-team-research/equipment-tech/commercial-participation',
        ],
      },
      {
        text: '作战应用与聚焦场景',
        link: '/blue-team-research/operations-application/',
        collapsible: true,
        children: [
          '/blue-team-research/operations-application/',
          '/blue-team-research/operations-application/regional-conflicts',
          '/blue-team-research/operations-application/orbital-confrontation',
          '/blue-team-research/operations-application/kill-chain-focus',
          '/blue-team-research/operations-application/scenario-analysis',
          '/blue-team-research/operations-application/crosswalk',
        ],
      },
      {
        text: '资料共享与知识库',
        link: '/blue-team-research/knowledge-rag/',
        collapsible: true,
        children: [
          '/blue-team-research/knowledge-rag/',
          '/blue-team-research/knowledge-rag/search-metadata',
          '/blue-team-research/knowledge-rag/rag-roadmap',
        ],
      },
    ],
  },
]

export default <SidebarConfig>{
  '/glossary/': glossarySidebar,
  '/background/': backgroundSidebar,
  '/resources-tools/': resourcesToolsSidebar,
  '/blue-team-research/': blueTeamResearchSidebar,
  '/space-news/': spaceNewsSidebar,
  '/en/space-news/': spaceNewsSidebar,
  /** 全屏教学沙盘：不挂载目录型侧边栏（导航用顶栏即可） */
  '/satellite-simulation/': false,
  '/what-is-cislunarspace/': whatIsCislunarspaceSidebar,
  '/cislunar-orbits/': cislunarOrbitsMainSidebar,
  '/research-frontiers/': researchFrontiersMainSidebar,
  '/': homeSidebar,
}
